Skip `login` in the `finish` step if `-t` is specified
psss/tmt pull request #1933
Opened 2023-03-21 10:56 UTC by idorax

If option `--test` (`-t`) is specified, we should skip to log into the guest in finish phase as it has been done already.

Fix: #1918

2023-03-21 11:16 UTC, lukaszachy requested changes
Unfortunately this breaks `--step` and `--when` functionality:
Same reproducer.fmf with `tmt run login -t --step prepare`  - As a user I might want to login to the system before the execute step.

The `--when` breakage is questionable, however the main difference between `--test` and `--when` is login to 'execute' versus 'finish' step, which have different environment.
With that said I think there might be some valid use case to user `-t` and `--when` together.

2023-03-21 11:22 UTC, idorax commented
> Unfortunately this breaks --step and --when functionality ...

@lukaszachy, how about introducing a variable to record the action to log into the guest is done? If it's done, skip to the login action in finish step.

2023-03-21 11:52 UTC, lukaszachy commented
> > Unfortunately this breaks --step and --when functionality ...
> 
> @lukaszachy, how about introducing a variable to record the action to log into the guest is done? If it's done, skip to the login action in finish step.

IMO it is not necessary. Your approach is good, just stop the login only if there isn't `when` or `step` used. Current patch is too eager to stop the login.

From the options `--command` doesn't affect whether the login should happen or not, but `--test`, `--step` and `--when` do.

2023-03-21 13:20 UTC, idorax commented
> > > Unfortunately this breaks --step and --when functionality ...
> > 
> > 
> > @lukaszachy, how about introducing a variable to record the action to log into the guest is done? If it's done, skip to the login action in finish step.
> 
> IMO it is not necessary. Your approach is good, just stop the login in finish only if there isn't `when` and `step` used. Current patch is too eager to stop the login.

@lukaszachy, to check `when` or `step` used, looks we can keep using `opt('when')` or `opt('step')`.

```bash
$ find tmt -name "*.py" | xargs egrep -- "'--when|'--step"
tmt/steps/__init__.py:            '-s', '--step', metavar='STEP[:PHASE]', multiple=True,
tmt/steps/__init__.py:            '-s', '--step', metavar='STEP[:PHASE]', multiple=True,
tmt/steps/__init__.py:            '-w', '--when', metavar='RESULT', multiple=True,
```

Would you please help to paste a user case having `both -t and --when` or `-t, --when and --step`?

2023-03-21 13:30 UTC, lukaszachy commented
> Would you please help to paste a user case having `both -t and --when` or `-t, --when and --step`?

How about the opposite question - Why should we disallow that?

I've realized that  '-c CMD' can be used to workaround fact one cannot append 'prepare' or 'finish' step from the commandline (it would replace step definition from the plan) to do something on the guest.  
But I'm not sure how well one can combine options (e.g. `tmt run ... login -c 'date' login -t login --step prepare -c 'some prep magic' ...` ). I'll take a look later if you don't find it sooner.

2023-03-22 08:03 UTC, lukaszachy commented
While trying to create use case for `login -t  --when` I've realized that it behaves a bit surprising.

Current implementation is that `-t` logs into execute right after the test finishes and has same environment as the test (very easy to rerun the test) while `--when` logs into finish depending on the execute outcome.

IMO we could keep `login --when RESULT` work as is (login into finish step depending on the execute) however  the `login -t --when RESULT` should be changed to "log into execute right after the test depending on the test RESULT".

This would cover use case when User has several tests in the plan but want to login immediately after RESULT (usually fail or error) to investigate what has happened. Currently it is not easy as `-t` logs in after each test and login in finish is too late as later tests might change the SUT significantly.

WDYT @psss @happz @adiosnb @idorax ?

2023-03-31 12:26 UTC, thrix commented
/packit test

2023-04-18 08:49 UTC, adiosnb commented
> While trying to create use case for `login -t --when` I've realized that it behaves a bit surprising.
> 
> Current implementation is that `-t` logs into execute right after the test finishes and has same environment as the test (very easy to rerun the test) while `--when` logs into finish depending on the execute outcome.
> 
> IMO we could keep `login --when RESULT` work as is (login into finish step depending on the execute) however the `login -t --when RESULT` should be changed to "log into execute right after the test depending on the test RESULT".
> 
> This would cover use case when User has several tests in the plan but want to login immediately after RESULT (usually fail or error) to investigate what has happened. Currently it is not easy as `-t` logs in after each test and login in finish is too late as later tests might change the SUT significantly.
> 
> WDYT @psss @happz @adiosnb @idorax ?

Yeah, for me it makes sense to be able to combine these parameters to be able to login to a server after each failed or error test. 

+1 for me

2023-04-18 10:10 UTC, lukaszachy commented
This is the usual 'issue looks easy at first but later it explodes' example.

Conclusion from the hacking session:
`login -t --when RESULT` should login to the guest immediately after the test (so it has to be in the execute) if the test ended with RESULT . No additional login in the finish should happen unless requested.

We allow multiple `--step` and `--when` so one way to implement this could be to implicitly use `--step execute` if `-t` is used.
So `login -t --when RESULT ` would be the same as `login -t --when  RESULT --step execute` thus the login in finish will not happen.
However user can request `login -t --when RESULT --step finish` and because of the `-t` it would be as if `login -t --when RESULT --step finish --step execute` was used and login will happen in the execute (after each test with RESULT) and finish (if any test has RESULT). IF user doesn't want to login in execute for this command line they shouldn't specify `-t` option.

I'm not sure that mutiple `login` on the commandline work correctly so let's support single login command with several options.

This should ready for the  future once multiple subcommands can be used properly (the logic of login command can stay the same).

2023-04-18 10:15 UTC, lukaszachy commented
> Would you please help to paste a user case having both -t and --when or -t, --when and --step

To finally reply the use cases:

`-t --when` : As tmt user I want to login to the guest with the same environment as the test immediately after that test finishes with RESULT so I can investigate why if finished in such result (e.g. --when fail to see why test fails)

`-t --when --step`: As a tmt user I want to investiage test result in execute step but I want to  login to the guest in other steps than execute as well.

2023-04-20 15:41 UTC, lukaszachy commented
My testing plan:

```
/p:
  execute:
    how: tmt
  discover:
    how: fmf
  provision:
    how: container

/t:
  /good:
    test: 'true'

  /bad:
    test: 'false'
```

The `tmt run login -t` works as expected -- logs in 'execute' step immediately after each test, no login in finish

But `tmt run login -t --when fail` however logs in 'finish' and there is no way to stop that (adding --step execute makes login happen at the end of 'execute' step (once all tests are finished')

Could the login in 'finish' be disabled when '-t --when' is set but '--step finish' is not?
So `tmt run login -t --when fail` will login only after '/t/bad' but I can ask tmt to login in finish as well by `tmt run login -t --when fail --step finish`

2023-05-03 14:08 UTC, adiosnb commented
> My testing plan:
> 
> ```
> /p:
>   execute:
>     how: tmt
>   discover:
>     how: fmf
>   provision:
>     how: container
> 
> /t:
>   /good:
>     test: 'true'
> 
>   /bad:
>     test: 'false'
> ```
> 
> The `tmt run login -t` works as expected -- logs in 'execute' step immediately after each test, no login in finish
> 
> But `tmt run login -t --when fail` however logs in 'finish' and there is no way to stop that (adding --step execute makes login happen at the end of 'execute' step (once all tests are finished')
> 
> Could the login in 'finish' be disabled when '-t --when' is set but '--step finish' is not? So `tmt run login -t --when fail` will login only after '/t/bad' but I can ask tmt to login in finish as well by `tmt run login -t --when fail --step finish`

What do you think about extending the login test set with these cases?

2025-11-11 17:02 UTC, LecrisUT commented
Is still still relevant?

2026-01-23 11:11 UTC, vaibhavdaren commented
Discussion Continued on : https://github.com/teemtee/tmt/issues/1918#issuecomment-3789758619

2026-01-28 14:44 UTC, vaibhavdaren commented
Notes on login options.
| Options | Behavior | Login Count |
| :--- | :--- | :--- |
| (none) | Login at end of last enabled step (default: finish) | 1 |
| `-t` | Per-test login only (after each test in execute) | # of tests |
| `-t --when fail` | Per-test login only after failing tests | # of failed tests |
| `-t --step finish` | Per-test login + login at finish step (additive) | # of tests + 1 |
| `--when fail` | Login at finish step only if any test failed | 0 or 1 |
| `--when fail --step report` | Login at report step only if any test failed | 0 or 1 |
| `--step execute` | Login at execute step | 1 |
| `-t --when fail --step finish` | Per-test after fail + at finish (additive) | # of failed tests + 1 |

2026-02-03 18:00 UTC, vaibhavdaren commented
/packit test

2026-02-03 18:50 UTC, vaibhavdaren commented
/packit test

2026-02-03 19:29 UTC, tcornell-bus commented
/packit build

2026-02-05 09:39 UTC, vaibhavdaren commented
> The only row from your table that I do not see represented as a test is the last:
> 
> > -when fail --step report | Login at report step only if any test failed | 0 or 1
> 
> Could that test be added? Not sure the best place for it, maybe `tests/login/when.sh`?

Ammeneded the commit : Added the test in 5c2f711da66e645b9e7f1d94bdd81bb9b446a5b6.

2026-02-05 11:57 UTC, LecrisUT commented on tests/login/step.sh
> +        # Run all steps, cleanup will be the last completed step
The comment is vague. Yes, cleanup is the last step, but that is not the step that is associated with the login. This does uncover an issue that when we run the cleanup, the provisioned guest is gone, which would be relevant for provision container, vm, etc. An issue to be followed-up though.

2026-02-05 12:21 UTC, LecrisUT commented on docs/releases/pending/4481.fmf
> +  for conditional per-test login.
Be more concise on the changes done here, explicitly about the behavior changes, not of the implementation details (-1 to stuff like "help text now explains"), something like

> ``tmt run login --test`` no longer includes a login step at the last enabled step, instead
> only after the test executions. Explicitly use ``--step`` if you want to also login at a specific step.

2026-02-05 12:21 UTC, LecrisUT commented on docs/releases/pending/4481.fmf
`/stories/cli/run/login` could also use some clarification on that.

2026-02-05 12:29 UTC, LecrisUT commented on tmt/steps/__init__.py
> +            'Use --when <result> for conditional login (e.g. --when fail).',
Make it a multi-line string please. Also we have text formatting if you use rst's double-tick (see `tmt --help`), please use it.

2026-02-05 12:37 UTC, LecrisUT commented on tmt/steps/__init__.py
> +        guestless_steps = ['discover']
`cleanup` and `report` is also guestless. Technically `provision` is also guestless (I am not sure why), but that one should be having the login. One programmatic way to find if it is guestless is `issubclass(step._plugin_base_class, GuestlessPlugin)`, but that should be exposed at the `Step` class level instead of in there.

2026-02-05 12:39 UTC, LecrisUT commented on tmt/steps/__init__.py
> +        step_name = self.parent.name if self.parent else "unknown"
When is `self.parent` not defined as a `Step`? This and type-hinting are saying a different thing, so please fix the wrong one.

2026-02-05 15:12 UTC, vaibhavdaren commented on tmt/steps/__init__.py
> +        step_name = self.parent.name if self.parent else "unknown"
The Login instance is always created with a Step parent.  Fixed in subsequent commit.

2026-02-05 17:47 UTC, happz commented on tmt/steps/__init__.py
> +            'Disables default step-level login unless combined with --step.',
Please, use proper multiline string. Click and tmt can handle it. See e.g. https://github.com/teemtee/tmt/blob/main/tmt/cli/_root.py#L284

2026-02-05 17:48 UTC, happz commented on tmt/steps/__init__.py
> +            )
Wouldn't `warn` be more fitting? The situations seems like a misuse or mistake, hence warning. It's not a business as usual, just another step in the expected workflow.

2026-02-05 19:40 UTC, vaibhavdaren commented on tmt/steps/__init__.py
> +            )
Yes, makes sense. Addressed in 608855085ca0ddf0ff349c830ef184a513f29474.

2026-02-05 19:40 UTC, vaibhavdaren commented on tmt/steps/__init__.py
> +            'Disables default step-level login unless combined with --step.',
Addressed in 608855085ca0ddf0ff349c830ef184a513f29474.

2026-02-08 01:08 UTC, vaibhavdaren commented
/packit build

2026-02-09 14:26 UTC, psss commented
/packit build

2026-02-09 17:00 UTC, LecrisUT commented on stories/cli/run.fmf
> +            to investigate the environment while it is still fresh.
```suggestion
            As a user I want to log into the guest after each test.
```

2026-02-09 17:03 UTC, LecrisUT commented on stories/cli/run.fmf
> +            tmt run login --test --when fail
```suggestion
```
The `--when` is covered by the previous section. `--test` here does not do anything to it.

2026-02-09 17:11 UTC, LecrisUT commented on tmt/steps/__init__.py
> +        guestless_steps = ['discover']
Still relevant. What to do with `cleanup` and `report`?

2026-02-10 09:43 UTC, vaibhavdaren commented
/packit build

2026-02-10 09:50 UTC, psss commented on stories/cli/run.fmf
> +            login. Use --step to also login at a specific step.
```suggestion
            login. Use ``--step`` to also login at a specific step.
```

2026-02-10 10:02 UTC, vaibhavdaren commented
/packit build

2026-02-10 13:39 UTC, psss commented
/packit build

2026-02-10 18:27 UTC, vaibhavdaren commented
/packit build

2026-02-10 20:30 UTC, psss commented
/packit test

2026-02-11 06:56 UTC, psss commented
/packit retest-failed

2026-02-11 09:48 UTC, vaibhavdaren commented
/packit test

2026-02-11 09:52 UTC, vaibhavdaren commented
/packit build

2026-02-11 17:30 UTC, psss commented
/packit build

2026-02-11 21:36 UTC, psss commented
/packit retest-failed

2026-02-12 05:21 UTC, psss commented
/packit retest-failed

2026-02-12 06:51 UTC, psss commented
All green except for `beaker-client` problem which is fixed/workarounded by #4572.

2026-02-12 06:59 UTC, psss commented on tmt/steps/__init__.py
> +        guestless_steps = ['discover']
Completely removed from the code.

2026-02-12 07:03 UTC, merged