tmt.spec: disable shebang mangling
psss/tmt pull request #341
Opened 2020-09-08 09:00 UTC by martinky82

2020-09-08 09:49 UTC, psss commented
Thanks for the fix, @martinky82. Looking at the [packaging guidelines](https://docs.fedoraproject.org/en-US/packaging-guidelines/#_shebang_lines) it seems there is also an option to disable the functionality for specific paths, which is recommended. Could you please update the pull request with using `%__brp_mangle_shebangs_exclude`?

Can you also use a release-notes-copy-pastable [commit message](https://tmt.readthedocs.io/en/latest/contribute.html#commits)? Thanks.

2020-09-08 09:50 UTC, psss requested changes

2020-09-08 09:50 UTC, psss commented on tmt.spec
> +# shebang mangling breaks ContOS experience
```suggestion
# Shebang mangling breaks run.sh in CentOS 6 containers
```

2020-09-08 12:13 UTC, psss commented
This does not seem to be working:

    make rpm
    ...
    rpmbuild --define '_topdir /home/psss/git/tmt/tmp' -bb tmt.spec
    error: line 28: Unknown tag: %__brp_mangle_shebangs_exclude /bin/bash
    make: *** [Makefile:47: rpm] Error 1

In order to check the shebang is as expected:

    head -1 $(rpm -ql python3-tmt|grep run.sh)

Also, could you please rebase on the latest master?

2020-09-08 12:37 UTC, psss commented
/packit build
/packit test

2020-09-09 06:29 UTC, martinky82 commented
It seems we're affected by this bug here:

https://bugzilla.redhat.com/show_bug.cgi?id=1839170

2020-09-09 06:36 UTC, psss commented
Could we possibly use `%__brp_mangle_shebangs_exclude_from` to disable mangling? If I understand it correctly, this macro be used to specify paths which should be ignored. @hroncok, would you have any other recommendation?

2020-09-09 07:20 UTC, hroncok commented
I don't understand. You build the RPM on recent Fedora or EPEL 8 and install it to CentOS 6?

2020-09-09 08:21 UTC, psss commented
@hroncok, the issue #339 is about a `run.sh` script which is packaged in `python3-tmt` and used for executing tests in a detached way (the script is run on the remote guest to execute all tests). But when tests are executed against a CentOS 6 container the script fails, because there is no `/usr/bin/bash` in the minimal images. We want to keep `/bin/bash` in the shebang so that it works across all distros and execution methods.

2020-09-09 08:26 UTC, hroncok commented
> the script is run on the remote guest to execute all tests

How is this achieved? Is it possible to package the script as a non-executable file and toggle the exec perm upon usage on remote guest? That would be the most clean solution.

If that is not possible, I'd set `%__brp_mangle_shebangs_exclude_from` to the script's path.
Note that it is supposed to be a regex, so better escape the dot.

2020-09-09 08:48 UTC, psss commented
> Is it possible to package the script as a non-executable file and toggle the exec perm upon usage on remote guest? That would be the most clean solution.

Thanks for the hint. I think we could do that. The implementation should be quite straightforward.

2020-09-10 14:07 UTC, psss commented
Here's the [relevant code](https://github.com/psss/tmt/blob/master/tmt/steps/execute/detach.py#L68) for the `detach` executor.

2020-09-14 05:39 UTC, closed without merging