Implement --follow option
psss/tmt pull request #499
Opened 2020-12-22 14:03 UTC by FrNecas

Something up for discussion: do we want to exactly mimic `tail -f` behaviour or do we want to somehow modify it? Tail shows the last 10 lines in the file and then adds more once they are added. I followed this approach as I think it's pointless to show the whole log but it may be useful to show at least a few of the last lines to give context.

Resolves: #482

2021-01-04 12:13 UTC, psss requested changes
Thanks for implementing this. Looks fine. Added just a couple of minor suggestions.

2021-01-04 12:13 UTC, psss commented on tmt/base.py
> +        if context.params.get('follow') and not id_specified:
Specifying `--id` ends up with an error. Let's simplify the check a bit:

```python
if context.params.get('follow') and id_ is None:
```

And remove the preceding line altogether.

2021-01-04 12:13 UTC, psss commented on tmt/base.py
> +    def follow(self):
Please, include a docstring.

2021-01-04 12:13 UTC, psss commented
/packit test

2021-01-26 08:49 UTC, FrNecas commented on tmt/cli.py
> +    help='Output the logfile as it grows.')
I think we could but wouldn't it be a bit confusing adding `-F` to run when -F is already used in some steps (for example flavor in minute or --filter in discover --how fmf)?

2021-01-26 09:06 UTC, psss commented on tmt/cli.py
> +    help='Output the logfile as it grows.')
Well, I expect there will be more such collisions and I don't see a big problem in that. On the other hand, we can wait a bit with the short option until other new features are implemented (which could bring another candidate for the `-F` shortcut). I'm ok with both.

2021-01-26 09:16 UTC, FrNecas commented on tmt/cli.py
> +    help='Output the logfile as it grows.')
Ok, lets stay with the long option only for now; we can add the short one later if the need arises and we don't find a better use for `-F`.

2021-01-26 18:08 UTC, psss approved these changes
Thanks for addressing all issues. Looks good.

2021-01-26 18:09 UTC, merged