534: Use case: As a test author I want to create new test in the current directory using specified template
psss/tmt pull request #549
Opened 2021-02-11 22:52 UTC by dkarpele

I added `try` expression to solve exception with the non-existent template:
```
$ tmt test create -t AHOJ test
Directory '/tmp/test_tmt/test' created.
Traceback (most recent call last):
  File "/usr/bin/tmt", line 8, in <module>
    tmt.cli.main()
  File "/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/tmt/cli.py", line 371, in create
    tmt.Test.create(name, template, context.obj.tree, force)
  File "/usr/lib/python3.8/site-packages/tmt/base.py", line 284, in create
    path=metadata_path, content=tmt.templates.TEST_METADATA[template],
KeyError: 'AHOJ'
```

I didn't find a better solution then using `os.getcwd()` method for NAME='.' case. 
```
$ cd test_tmt/
$ mkdir -p some/nice/dir/structure
$ cd some/nice/dir/structure
$ tmt tests create -t beakerlib .
Test metadata '/tmp/test_tmt/some/nice/dir/structure/main.fmf' created.
Test script '/tmp/test_tmt/some/nice/dir/structure/test.sh' created.
[dkarpele@redhat structure]$ cd /tmp/test_tmt/ ; tree
.
├── plans
│   └── example.fmf
└── some
    └── nice
        └── dir
            └── structure
                ├── main.fmf
                └── test.sh

5 directories, 3 files
[dkarpele@redhat test_tmt]$
```

2021-02-12 09:57 UTC, dkarpele commented
Hi @psss 
The changes in this PR can not differ depending on fedora/epel-8 etc. I'm not sure that the test failures are relevant.

2021-02-16 12:37 UTC, psss commented
>  The changes in this PR can not differ depending on fedora/epel-8 etc. I'm not sure that the test failures are relevant.

Yes, these are CI issues, there were some substantial changes in the implementation so we have to be patient until the dust settles down. Anyway, I've also did some test cleanup recently. Going to rebase on the latest master.

2021-02-16 12:46 UTC, psss requested changes
Thanks for writing the improvement! Looks good, just a few minor comments. Could you please enhance the `tmt test create --help` message so that the new dot syntax is documented? Also, adding a simple test `/tests/test/create` would be nice (it seems we have only covered plan and story creation so far).

2021-02-16 12:46 UTC, psss commented on tmt/base.py
> +                path=metadata_path, content=tmt.templates.TEST_METADATA[template],
Could you please break the long line?

2021-02-16 12:46 UTC, psss commented on tmt/base.py
> +                "Invalid template '{}'.".format(template))
```suggestion
                f"Invalid template '{template}'.")
```

2021-02-16 20:35 UTC, dkarpele commented
@psss thank you for review!
I've updated the PR according to your comments.

2021-02-19 16:14 UTC, psss approved these changes
Thanks for fixing all issues and writing a very nice test! :) I've squashed your commits, rebased on the latest master and added just a couple minor adjustments.

2021-02-20 08:42 UTC, merged

2021-02-20 16:18 UTC, dkarpele commented
Thank you Petr!