Search for testcase if already created inside TCMS before creating new one
psss/tmt pull request #568
Opened 2021-02-22 09:49 UTC by jscotka

This is important in case of virtual hierarchy. If you remove `extra-nitrate:` key.

My usecase is:

I'm using automatic conversion of fmf data from python unittest to FMF files.
and in case I'll remove TCMS key (by mistake, or want to regenerate all FMF files), it will create new TCMS testcases, it does not try to find if there already exist any node with the same FMF identifier in TCMS.

2021-02-22 19:51 UTC, psss commented
Thanks for the patch. This looks reasonable, however, I would propose to introduce an option like `--no-duplicate` to enable this feature. Or perhaps, make this default and `--allow-duplicates` when needed. Let's discuss the better default on the hacking sesion. Anyway, could you please move the duplicate check functionality into a separate function?

2021-02-23 09:16 UTC, jscotka commented
> Thanks for the patch. This looks reasonable, however, I would propose to introduce an option like `--no-duplicate` to enable this feature. Or perhaps, make this default and `--allow-duplicates` when needed. Let's discuss the better default on the hacking sesion. Anyway, could you please move the duplicate check functionality into a separate function?

makes sense, created separated function, what will return list of all tcms cases. and options we'll discuss.

2021-02-23 11:58 UTC, lukaszachy commented
For boolean options I like clicks '--flag/--no-flag' pairs, so I propose to call the options `--duplicate/--no-duplicate` with `--no-duplicate` as a default.

2021-02-23 13:38 UTC, lukaszachy requested changes

2021-02-23 13:43 UTC, jscotka commented on tmt/export.py
> +                nitrate_case = create_nitrate_case(test)
Ah, thanks, I've so often changed the code that it stops working :-)

2021-02-23 14:00 UTC, lukaszachy approved these changes

2021-03-02 13:09 UTC, jscotka commented
@psss @lukaszachy please consider adding it to milestone 1.4

2021-03-02 21:44 UTC, psss commented
Thanks for the improvements. I've proposed a couple of adjustments in e63bb23. Namely:

 * Simplify option handover by using `self.opt()`.
 * Compare fmf id using `dict` rather than `yaml`.
 * Support both `--duplicate` and `--no-duplicate`.

Please, have a look and check whether the changes are ok. Thanks.

2021-03-04 11:14 UTC, jscotka commented
> Thanks for the improvements. I've proposed a couple of adjustments in [e63bb23](https://github.com/psss/tmt/commit/e63bb23e142deda3721162cd0ec36a012b8ad2ae). Namely:
> 
> * Simplify option handover by using `self.opt()`.
> * Compare fmf id using `dict` rather than `yaml`.
> * Support both `--duplicate` and `--no-duplicate`.
> 
> Please, have a look and check whether the changes are ok. Thanks.

Yep, seem very well

2021-03-04 20:29 UTC, merged