prvosion: ansible: Pass plan environment
psss/tmt pull request #774
Opened 2021-05-17 11:28 UTC by fernflower

Prior to this change environment variables declared via in plan's
environment were ignored.

2021-05-17 12:06 UTC, psss requested changes
Would be nice to include a corresponding test coverage. What about extending a bit the `/tests/prepare/ansible` test? The commit message has a typo. Let's not use prefixes in the commit summary as suggested in the [commit recommendations](https://tmt.readthedocs.io/en/latest/contribute.html#commits). Thanks.

2021-05-17 12:06 UTC, psss commented on tmt/steps/provision/__init__.py
> +            f'{environment}'
```suggestion
            f'{self._export_environment()}'
```
Let's use the method directly.

2021-05-17 12:09 UTC, psss commented
> That's critical for leapp e2e tests to run properly with tmt

Marking as a `must have` for `1.6`.

2021-05-17 17:22 UTC, fernflower commented
> > That's critical for leapp e2e tests to run properly with tmt

@psss remember when I said, that I was wrong and it isn't critical as I found a workaround? Well turns out I didn't and it is blocking e2e test transition for real. 

Added tests, F34 job is failing though :(

2021-05-18 13:19 UTC, psss approved these changes
Thanks for providing the test coverage. During the review I realized that the `local` provision has the same problem so I've covered that in bb68cad together with extending the test coverage to actually verify `local` and `virtual` provision methods as well.

2021-05-18 15:18 UTC, lukaszachy approved these changes

2021-05-18 15:21 UTC, merged