Use testcloud for image url guessing
psss/tmt pull request #827
Opened 2021-07-08 12:44 UTC by frantisekz

Fixes https://github.com/psss/tmt/issues/514 ; uses testcloud to guess qcow2 url for short distro handles.

Needs latest testcloud git snapshot, available in  https://copr.fedorainfracloud.org/coprs/frantisekz/testcloud-wip/ .

Ubuntu and Debian support is not working, at least in m testing (url to qcow gets guessed correctly, vm boots up but ssh is not working, it is with plain testcloud).

2021-07-08 13:45 UTC, psss requested changes
Thanks a lot for improving this! Looks good to me and works as expected, or rather as a charm :) Just a couple of minor comments added. Please, break also long lines to make `pre-commit` happy ;-)

I guess we can resolve the ubuntu/debian problem later if the issue is not obvious I would not block the PR on this.

2021-07-08 13:45 UTC, psss commented on tmt/steps/provision/testcloud.py
> -                response = self._get_url(KOJI_URL, 'check Fedora composes')
Seems the `KOJI_URL` constant is not needed anymore.

2021-07-08 13:45 UTC, psss commented on tmt/steps/provision/testcloud.py
> +        # Plain name matches means we want the latest release
```suggestion
        # Plain name match means we want the latest release
```

2021-07-08 14:05 UTC, psss approved these changes
Thanks for the quick fixes, looks good now, feel free to squash.

2021-07-08 14:31 UTC, psss commented
Just noticed one issue:

```
> tmt run provision
/var/tmp/tmt/run-061

/plans/default
    provision
        how: virtual
        image: fedora
        user: root
        memory: 2048 MB
        disk: 10 GB
        progress: booting...
Python libguestfs bindings are missing, guest detection won't work properly!
        distro: Fedora 34 (Cloud Edition)
        summary: 1 guest provisioned
```

Could we get rid of the warning message? Or is it an essential problem?

2021-07-08 14:43 UTC, psss commented
This is blocked until the fresh `testcloud` makes it into the stable Fedora repos.

2021-07-09 14:07 UTC, frantisekz commented
> Could we get rid of the warning message? Or is it an essential problem?

This is more of an essential problem, We now rely on python3-libguestfs to decide which networking device shall testcloud use (RHEL 7 and RHEL (8 + 1) are mutually exclusive). This isn't caused by this tmt pr, it's part of testcloud-0.6.0.

Right before cutting a new testcloud release, I've added an api way ( https://pagure.io/testcloud/pull-request/111 ) to work around the warning by voluntarily specifying desired pci net device and so disabling the auto detection attempt by testcloud. 

Testcloud from repositories now requires the necessary python guestfs bindings, however, they're not on pypi unfortunately ( https://bugzilla.redhat.com/show_bug.cgi?id=1075594 ).

2021-07-12 07:35 UTC, psss commented
I see, thanks for clarification. So this means there will be no warning when `tmt` is run from the `rpm` package. Would be nice to silence the warning when installed by `pip` as well. So do I understand it correctly that the newly introduced config for custom pci net device should/could be used in the `testcloud` plugin?

2021-07-12 08:45 UTC, psss commented
Rebased on the latest master to fix tests failing on rawhide.

2021-07-15 09:54 UTC, psss commented
/packit test

2021-07-15 14:05 UTC, merged

2021-07-16 15:44 UTC, FrNecas commented on tmt.spec
> +Requires: python%{python3_pkgversion}-testcloud >= 0.6.0
It is also necessary to update `setup.py` (I ran into exceptions due to having 0.5.0 and was wondering why it wouldn't update through pip ;)). I will create a PR for that. I've also ran into some problems with testcloud 0.6.0 and it does not work on my machine.