Add specification for hostname
psss/tmt pull request #980
Opened 2021-12-13 17:12 UTC by thrix

For Beaker it is possible to choose machine according to hostname.
This is used widely and should be supported.

We should be able to choose hostname via regular expression matching.

Resolves #942 

Signed-off-by: Miroslav Vadkerti <mvadkert@redhat.com>

2021-12-13 17:12 UTC, thrix commented
@happz ptal

2021-12-13 17:13 UTC, thrix commented
@psss @lukaszachy I am a bit confused from regex matching operator:

1. we have it now `=~` but in context we use `~=` which might be a bit confusing maybe?

2. seems it is common to use does not match regex, we need to decide how that should be written `=!~` or `! =~` or something else?

2021-12-13 18:12 UTC, jirka-h commented
I vote for `! =~`.

2021-12-13 19:27 UTC, happz commented
+1 on `hostname`.

My two cents: `=~` + `!~` would look best to me, but if you already have an existing implementation that's using `~=`, I'd suggest aligning HW requirements with that implementation (on the assumption regex operators in HW requirements are rarely used so far), and then I'd vote for `~=` and `~!` (both replacing `=` with `!` while keeping `~` to make clear it's regex operator). `=!~` uses both `=` and `!` (yeah, I know, `!=` does the same...) and it's one extra character, and `! =~` contains a space (and two extra characters...). Bash uses special `!` before the test, Perl has `!~`, just like Prometheus. `~` seems to be commonly used. I'm biased, sue me ;)

There's also negative lookahead, `hostname: =~ (?!kvm-01.*)` ;)

2021-12-14 08:02 UTC, lukaszachy commented
I'd prefer `~` and `!~` as a new regexp operator because it will stand out more from the existing:
```
binary_operator ::= '==' | '!=' | '<' | '<=' | '>' | '>=' |
    '~=' | '~!=' | '~<' | '~<=' | '~>' | '~>='
```

IMO if we have both "~=" and "=~" it will be very hard to stop the typo (or remember which is which).

2021-12-14 11:54 UTC, jirka-h commented
> I'd prefer `~` and `!~` as a new regexp operator because it will stand out more from the existing:
+1 from me!

2022-01-04 11:10 UTC, lukaszachy requested changes
Could you change to `~` and `!~` as operator? See the discussion.

2022-01-05 16:33 UTC, psss approved these changes
> I'd prefer `~` and `!~` as a new regexp operator because it will stand out more from the existing:

I like these two as well. Adjusted the spec as proposed and rebased on the latest master.

2022-01-27 21:36 UTC, merged